# configs/config.yaml

models:
  random_forest:
    module: sklearn.ensemble
    class: RandomForestClassifier
    params:
      n_estimators: 200
      max_depth: 10
      random_state: 42

  logistic_regression:
    module: sklearn.linear_model
    class: LogisticRegression
    params:
      solver: lbfgs
      max_iter: 1000
      random_state: 42

training:
  test_size: 0.2
  random_state: 42
  stratify: true

paths:
  raw_data: "data/raw_data/project_data.csv"
  processed_data: "data/processed_data/final_processed_data.csv"
  trained_model: "models/trained_models/best_model.pkl"
  scaler: "models/model_artifacts/scaler.pkl"
  evaluation_results: "models/evaluation_results/model_comparison.csv"

split:
  test_size: 0.2
  random_state: 42
